# _config.yml
title: 나의 블로그
description: 블록체인 리터러시를 충족하는 공간
encoding: utf-8
locale: ko_KR

# Jekyll 관련 설정
markdown: kramdown # 마크다운 파서 지정
theme: minima      # Jekyll 기본 테마 사용
plugins:
  - jekyll-feed
  - jekyll-sitemap
